### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Tomomoto10** [santacrab2/PKHeXMAUI#13]
Hey, i see youre still actively updating this which is awesome. Could i suggest a couple features? 

-Open Save / Export Save as its own menu on the side bar (outside of settings)
-The ability to have a different home screen, the first thing i do every time i open the app is go into settings, load save, open box. as it currently  opens on a random illegal genesect in the editor, when really it should open on the boxes so you can select a pokemon to edit after loading from the side bar. 
-Batch Import Pokemon files / Export/Import Entire boxes. This would help so much with completing the national dex, as of now pkhex desktop is the option for bulk transfer as you can have 2 instances and drag + drop or i think bulk save now?. I tried split screening 2 instances on android but it drags the box ID not the Pokemon info across from one instance to another and just copies what was originally "set" in the box you copy to. 

Great app otherwise, keen to see it evolve!

**Comment by santacrab2** [comment]
Thank you I am glad you are enjoying the app!
1. For now I am planning on adding a file menu to the side menu and I will put Open, save pkm, and export save there. This will allow me to merge the button on point 3.
2. The main loading page is not changing because of the way MAUI shell apps load and that I would have to change a lot of code on the back-end just to remove a tap. PKHeX Desktop also loads with that "random illegal genesect" I just have screen size limitations and can't fit the box on the same page. 
![image](https://github.com/user-attachments/assets/8efe8bb6-1dee-4eb1-9276-af04098b6e19)
3. Batch importing is already a thing, it can handle single PKM files, a group of PKM files, Mystery gift wondercards, PC box bins, and encounter files. You import them through Open PKM. I can see how this is not intuitive though, so I will work on merging this and the save file opener all into one button as PC PKHeX does. I will add the batch export button likely under Box/Party menu.

To address your attempt to have two instances open, phone's don't really allow data dragged between instances like that as far as I am aware. The best way to do this until I can add this features would be to save the files and then import them into the new save, which obviously 1x1 is not ideal.

edit: Good timing though because I just wrapped up a section and so these will just move to the top of my to-do list!

**Comment by santacrab2** [comment]
Thought further on this, I have an idea that I will play around with for setting preferred "Home Page" but no promises.

**Comment by Tomomoto10** [comment]
Youre an absolute legend, thanks for responding so clearly on each!  
I fully understand any limitations and dont expect any miracles, but sounds like youre all over it and look forward to future updates!

**Comment by santacrab2** [comment]
Just an update: about half way done. I was able to add everything suggested. I am just working on the batch export stuff now, but I've decided to add more than I originally planned so its taking a bit longer than originally expected. Preferred landing page was sorted out without the need for major changes and is now a setting for the user to set.

**Comment by Tomomoto10** [comment]
Smashing it out! Appreciate the update. 
Just another one for the list while your there if its possible, can the top bar follow system theme or just be black or dark grey? Or can the window be made to fit?
![Screenshot_20241218-145610.png](https://github.com/user-attachments/assets/17526198-f337-4992-9b73-56992d11c5d8)

**Comment by Tomomoto10** [comment]
Dont know if its device specific. 
Im on Pixel 7pro, GrapheneOS. 
Eg. This is the Github app for reference 
![Screenshot_20241218-150146.png](https://github.com/user-attachments/assets/9b0f8db7-a3dc-465d-9cc4-3d67a5f7de1a)

**Comment by santacrab2** [comment]
Already fixed, the white bar at the top was from a change in Android 15 i had to handle.

edit: Will be adjusted in the next release I am hoping to have out soon.

**Comment by santacrab2** [comment]
all suggestions added in latest release!
