### ISSUE TITLE
Incompatible with phone

### ISSUE THREAD

**Issue by vrork** [santacrab2/PKHeXMAUI#15]
It seems that the app is incompatible with either Android 10 or with a Galaxy S9+ (Exynos version).  Its what the app Apk Manager said and when i try to install it normally it gives me Error Parsing App

**Comment by Tomomoto10** [comment]
@vrork pretty sure the minimum android release is 11, i doubt it would be compatible even if you changed the lowest release to 10. Android 10 is pretty much extinct now..

**Comment by Tomomoto10** [comment]
Id recomend an aftermarket rom like LineageOS if your running a device that wont update to a newer official OS, you will only have troubles with and android that old.

**Comment by vrork** [comment]
Android 10 is still pretty common here is my country, A LOT of people here still use older phones due phones being expensive. Unfortunately using a non official rom is not a option for me.

**Comment by Tomomoto10** [comment]
Android 10 is just straight No longer supported in newer builds of anything from what im reading: 
"Beginning in August 2021, the Google Play Console requires that new apps target API level 30 (Android 11.0) or higher. Existing apps are required to target API level 30 or higher beginning in November 2021."

So not possible as android 10 is no longer supported as it doesnt meet the requirements anymore. You cant publish an app unless it meets these guidlines.
Without custom OS looks like your stuck.

**Comment by santacrab2** [comment]
Release 24.10.30 will be the last one to honor systems that old. Like Tomomoto pointed out the OS is no longer supported. Net9 added utilities that do not function on anything less than 12. I chose to keep supporting Android 11 because it just stopped receiving security updates in February, so its a fairly new shutdown. Eventually I will need to move on to only supporting 12+. Do bear in mind that if you choose to use old releases, no support is offered.
